"""
token-level unigram watermark encoder for llm memory entries.

implements the token-level unigram watermarking scheme from zhao et al.
(iclr 2024, arxiv:2306.17439) adapted for pre-existing memory entry strings.

the original paper targets text generated by a large language model: at generation
time, a prf-keyed green/red list biases the token probability distribution, and
detection counts green-list tokens via z-score.

for pre-existing memory entries (strings not generated by the watermarked llm),
we adapt the scheme via a two-stage paraphrase approach:
    1. embed: a small causal lm (gpt2) rephrases the entry with watermarked sampling:
       for each generated token, green-list logits are boosted by +delta before
       sampling, biasing the regeneration toward green-list vocabulary.
    2. detect: count green-list tokens in the (re)generated text and compute
       the standard unigram z-score over the output vocabulary.

the resulting z-scores are directly comparable to the zhao et al. paper because
detection operates on the same token-level statistics.  this is strictly stronger
than the character-level implementation (UnigramWatermarkEncoder) because:
    - vocabulary size is 50257 (gpt2) vs. 95 (printable ascii)
    - bias is applied at the probability distribution level, not post-hoc
    - z-scores are higher for the same text length

references:
    zhao et al. provable robust watermarking for ai-generated text.
    iclr 2024. arxiv:2306.17439.

    kirchenbauer et al. a watermark for large language models.
    icml 2023. https://arxiv.org/abs/2301.10226.

all comments are lowercase.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from typing import Dict, Optional, Set

import numpy as np

# ---------------------------------------------------------------------------
# optional dependency check
# ---------------------------------------------------------------------------

_TRANSFORMERS_AVAILABLE = False
try:
    import torch
    import torch.nn.functional as F
    from transformers import GPT2LMHeadModel, GPT2TokenizerFast

    _TRANSFORMERS_AVAILABLE = True
except ImportError:
    pass

# ---------------------------------------------------------------------------
# module-level model cache (one load per process)
# ---------------------------------------------------------------------------

_MODEL_CACHE: Optional[object] = None
_TOKENIZER_CACHE: Optional[object] = None
_VOCAB_SIZE: Optional[int] = None


def _load_model_and_tokenizer(model_name: str = "gpt2"):
    """lazy-load gpt2 model and tokenizer, cached globally."""
    global _MODEL_CACHE, _TOKENIZER_CACHE, _VOCAB_SIZE
    if _MODEL_CACHE is None:
        tok = GPT2TokenizerFast.from_pretrained(model_name)
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token
        model = GPT2LMHeadModel.from_pretrained(model_name)
        model.eval()
        _TOKENIZER_CACHE = tok
        _MODEL_CACHE = model
        _VOCAB_SIZE = tok.vocab_size
    return _MODEL_CACHE, _TOKENIZER_CACHE


# ---------------------------------------------------------------------------
# detection statistics dataclass
# ---------------------------------------------------------------------------


@dataclass
class TokenWatermarkStats:
    """statistics from token-level watermark detection."""

    z_score: float
    z_threshold: float
    green_count: int
    total_tokens: int
    green_proportion: float
    detected: bool
    gamma: float
    model_name: str

    def __str__(self) -> str:
        status = "DETECTED" if self.detected else "not detected"
        return (
            f"TokenWatermark({status}, z={self.z_score:.2f}, "
            f"green={self.green_count}/{self.total_tokens}"
            f"={self.green_proportion:.3f}, "
            f"thr={self.z_threshold})"
        )


# ---------------------------------------------------------------------------
# main encoder class
# ---------------------------------------------------------------------------


class TokenLevelWatermarkEncoder:
    """token-level unigram watermark encoder for llm memory entries.

    adapts the zhao et al. (iclr 2024) watermark to pre-existing text by
    using gpt2-based paraphrase regeneration with green-list biased sampling.

    args:
        gamma: fraction of vocabulary in the green list (default 0.25, as in paper)
        delta: logit bias added to green-list tokens at sampling time (default 2.0)
        z_threshold: z-score threshold for detection (default 4.0)
        max_new_tokens: max tokens to generate per entry (default 128)
        model_name: huggingface model name for the backbone lm (default "gpt2")
        secret_key: hex string seed for green-list prf (default "watermark")
        min_tokens: minimum tokens required for reliable detection (default 20)
        temperature: sampling temperature (default 0.8; lower = more deterministic)
        seed: numpy rng seed for reproducibility
    """

    def __init__(
        self,
        gamma: float = 0.25,
        delta: float = 2.0,
        z_threshold: float = 4.0,
        max_new_tokens: int = 128,
        model_name: str = "gpt2",
        secret_key: str = "watermark",
        min_tokens: int = 20,
        temperature: float = 0.8,
        seed: int = 42,
    ) -> None:
        if not _TRANSFORMERS_AVAILABLE:
            raise ImportError(
                "transformers and torch are required for TokenLevelWatermarkEncoder."
            )
        self.gamma = gamma
        self.delta = delta
        self.z_threshold = z_threshold
        self.max_new_tokens = max_new_tokens
        self.model_name = model_name
        self.secret_key = secret_key
        self.min_tokens = min_tokens
        self.temperature = temperature
        self._rng = np.random.default_rng(seed)
        # lazy-loaded
        self._model = None
        self._tokenizer = None
        self._vocab_size = None
        # green list: built once after model is loaded
        self._green_set: Optional[Set[int]] = None

    # -----------------------------------------------------------------------
    # public api
    # -----------------------------------------------------------------------

    def embed(self, content: str, watermark: str = "default") -> str:
        """embed watermark into content via gpt2 paraphrase with green-list bias.

        the entry is fed as a prefix to gpt2; each generated token is drawn
        from the distribution with green-list logits boosted by +delta.
        the regenerated continuation is appended to a semantic summary of the
        original entry, preserving meaning while embedding the watermark.

        args:
            content: the memory entry string to watermark
            watermark: watermark identifier (used to seed per-watermark prf)

        returns:
            watermarked string (rephrased with green-list bias)
        """
        self._ensure_loaded()

        # build green list seeded by both secret_key and watermark id
        green_set = self._get_green_set(watermark)

        # tokenize prefix (up to 256 tokens to leave room for generation)
        prefix_ids = self._tokenizer.encode(
            content, return_tensors="pt", max_length=256, truncation=True
        )

        # generate watermarked continuation with green-list logit bias
        generated = self._generate_watermarked(prefix_ids, green_set)
        return generated

    def extract(self, content: str, watermark: str = "default") -> Optional[str]:
        """detect watermark presence via z-score.

        returns:
            "detected:z=X.XX" if z-score exceeds threshold, else None
        """
        stats = self.get_detection_stats(content, watermark)
        if stats.detected:
            return f"detected:z={stats.z_score:.2f}"
        return None

    def detect(self, content: str, watermark: str = "default") -> float:
        """compute watermark confidence score (0.0–1.0) from z-score."""
        stats = self.get_detection_stats(content, watermark)
        if stats.z_score <= 0:
            return 0.0
        # sigmoid mapping: 0.5 at threshold, saturates above 2×threshold
        x = stats.z_score - self.z_threshold / 2.0
        return float(1.0 / (1.0 + math.exp(-x * 0.5)))

    def get_detection_stats(
        self, content: str, watermark: str = "default"
    ) -> TokenWatermarkStats:
        """compute full token-level z-score detection statistics.

        tokenizes content with gpt2 tokenizer and counts green-list tokens.
        the z-score follows the zhao et al. formula:
            z = (g - gamma * n) / sqrt(gamma * (1 - gamma) * n)
        where g = green token count, n = total token count.

        args:
            content: text to analyze
            watermark: watermark id (to select the correct green list)

        returns:
            TokenWatermarkStats with z_score, green_count, detected, etc.
        """
        self._ensure_loaded()
        green_set = self._get_green_set(watermark)

        token_ids = self._tokenizer.encode(content, add_special_tokens=False)
        n = len(token_ids)

        if n < self.min_tokens:
            return TokenWatermarkStats(
                z_score=0.0,
                z_threshold=self.z_threshold,
                green_count=0,
                total_tokens=n,
                green_proportion=0.0,
                detected=False,
                gamma=self.gamma,
                model_name=self.model_name,
            )

        green_count = sum(1 for tid in token_ids if tid in green_set)
        z = (green_count - self.gamma * n) / math.sqrt(
            self.gamma * (1.0 - self.gamma) * n
        )

        return TokenWatermarkStats(
            z_score=z,
            z_threshold=self.z_threshold,
            green_count=green_count,
            total_tokens=n,
            green_proportion=green_count / n,
            detected=z >= self.z_threshold,
            gamma=self.gamma,
            model_name=self.model_name,
        )

    # -----------------------------------------------------------------------
    # generation
    # -----------------------------------------------------------------------

    def _generate_watermarked(
        self, prefix_ids: "torch.Tensor", green_set: Set[int]
    ) -> str:
        """generate text with green-list logit bias using greedy/sampling."""
        import torch

        generated_ids = list(prefix_ids[0].tolist())
        n_new = 0

        with torch.no_grad():
            for _ in range(self.max_new_tokens):
                input_tensor = torch.tensor([generated_ids], dtype=torch.long)
                # limit context to last 1024 tokens (gpt2 max)
                if input_tensor.shape[1] > 1024:
                    input_tensor = input_tensor[:, -1024:]

                outputs = self._model(input_tensor)
                logits = outputs.logits[0, -1, :]  # [vocab_size]

                # apply green-list bias: +delta to all green token logits
                if self._vocab_size is not None:
                    for gid in green_set:
                        if gid < self._vocab_size:
                            logits[gid] = logits[gid] + self.delta

                # temperature sampling
                probs = F.softmax(logits / self.temperature, dim=-1)
                next_id = torch.multinomial(probs, num_samples=1).item()

                generated_ids.append(next_id)
                n_new += 1

                # stop at eos or natural sentence boundary
                if next_id == self._tokenizer.eos_token_id:
                    break
                # stop at period if we have generated enough tokens
                if n_new >= self.min_tokens:
                    tok_str = self._tokenizer.decode([next_id])
                    if "." in tok_str or "\n" in tok_str:
                        break

        # decode full generated text (prefix + new tokens)
        full_text = self._tokenizer.decode(
            generated_ids, skip_special_tokens=True, clean_up_tokenization_spaces=True
        )
        return full_text

    # -----------------------------------------------------------------------
    # green list construction
    # -----------------------------------------------------------------------

    def _get_green_set(self, watermark: str) -> Set[int]:
        """build the green token id set using prf keyed by secret_key + watermark."""
        # cache the default green set
        if watermark == "default" and self._green_set is not None:
            return self._green_set

        seed_material = f"{self.secret_key}:{watermark}"
        h = hashlib.sha256(seed_material.encode()).hexdigest()
        # use first 8 bytes of hash as seed for deterministic partitioning
        seed_int = int(h[:16], 16) % (2**31)
        rng = np.random.default_rng(seed_int)

        vocab_size = self._vocab_size or 50257
        n_green = int(vocab_size * self.gamma)
        all_ids = np.arange(vocab_size)
        rng.shuffle(all_ids)
        green_ids = set(all_ids[:n_green].tolist())

        if watermark == "default":
            self._green_set = green_ids
        return green_ids

    # -----------------------------------------------------------------------
    # model loading
    # -----------------------------------------------------------------------

    def _ensure_loaded(self) -> None:
        """lazy-load gpt2 model and tokenizer."""
        if self._model is None:
            self._model, self._tokenizer = _load_model_and_tokenizer(self.model_name)
            self._vocab_size = self._tokenizer.vocab_size


# ---------------------------------------------------------------------------
# comparison utilities
# ---------------------------------------------------------------------------


def compare_watermark_levels(
    content: str,
    char_encoder,
    token_encoder: "TokenLevelWatermarkEncoder",
    watermark: str = "eval",
) -> Dict[str, object]:
    """compare character-level and token-level watermark z-scores on same content.

    useful for ablation: shows the gain from token-level over character-level
    for entries of a given length.

    args:
        content: memory entry text
        char_encoder: UnigramWatermarkEncoder (character-level)
        token_encoder: TokenLevelWatermarkEncoder (token-level)
        watermark: watermark id

    returns:
        dict with char_z_score, token_z_score, char_detected, token_detected,
        z_score_gain, token_count, char_count
    """
    char_stats = char_encoder.get_detection_stats(content)
    token_stats = token_encoder.get_detection_stats(content, watermark)
    return {
        "char_z_score": char_stats.get("z_score", 0.0),
        "token_z_score": token_stats.z_score,
        "char_detected": char_stats.get("detected", False),
        "token_detected": token_stats.detected,
        "z_score_gain": token_stats.z_score - char_stats.get("z_score", 0.0),
        "token_count": token_stats.total_tokens,
        "char_count": char_stats.get("token_count", 0),
        "green_proportion_token": token_stats.green_proportion,
        "green_proportion_char": char_stats.get("green_proportion", 0.0),
    }
